USE sankalplr;

DROP TABLE IF EXISTS PatientRecords;
CREATE TABLE IF NOT EXISTS PatientRecords (
    id INT AUTO_INCREMENT PRIMARY KEY,
    observation_date DATE,
    case_id VARCHAR(255) UNIQUE,
    patient_name TEXT,
    facility TEXT,
    shift TEXT,
    admission_date TEXT,
    admission_time TEXT,
    gravida TEXT,
    parity TEXT,
    gestational_age TEXT,
    triage_under_30_min TEXT,
    risk_status TEXT,
    fhr_monitored TEXT,
    abnormal_fhr_action TEXT,
    partograph_filled TEXT,
    ancs_given TEXT,
    dose_count TEXT,
    labour_augmentation TEXT,
    indication_documented TEXT,
    oxytocin_monitoring TEXT,
    augmentation_appropriate TEXT,
    fundal_pressure_applied TEXT,
    complications_developed TEXT,
    complication_type TEXT,
    complication_description TEXT,
    complication_managed TEXT,
    senior_support_sought TEXT,
    referral_status TEXT,
    referral_delay TEXT,
    delivery_mode TEXT,
    csection_indication TEXT,
    csection_indication_other TEXT,
    assistant_name TEXT,
    anesthetist_name TEXT,
    outcome_of_labour TEXT,
    gender_of_baby TEXT,
    baby_cried_immediately TEXT,
    episiotomy_given TEXT,
    episiotomy_appropriate TEXT,
    amtsl_followed TEXT,
    av_oxytocin TEXT,
    av_placenta TEXT,
    eye_drops_given TEXT,
    initiation_of_breastfeeding TEXT,
    baby_stable TEXT,
    baby_dried TEXT,
    immediate_skin_to_skin TEXT,
    delayed_cord_clamping TEXT,
    baby_cried TEXT,
    stimulation_if_no_cry TEXT,
    bag_mask_if_needed TEXT,
    early_breastfeeding TEXT,
    clean_practices TEXT,
    birth_weight_taken TEXT,
    birth_weight_gms TEXT,
    vit_k_given TEXT,
    kmc_required TEXT,
    mother_counselled_kmc TEXT,
    kmc_given TEXT,
    kmc_duration_lr TEXT,
    kmc_provider TEXT,
    newborn_resuscitated TEXT,
    ref_nicu_sncu TEXT,
    outcome_of_baby TEXT,
    any_other_comments TEXT,
    timeOfDecision TEXT,
    timeOfIncision TEXT,
    dti_interval TEXT,
    is_timely TEXT,
    delay_reason TEXT,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
